// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "go_blog/internal/logic/blog"
	_ "go_blog/internal/logic/category"
	_ "go_blog/internal/logic/context"
	_ "go_blog/internal/logic/middleware"
	_ "go_blog/internal/logic/tags"
	_ "go_blog/internal/logic/user"
)
