// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_blog/internal/model"
)

type IAbout interface {
	About(ctx context.Context) (out *model.AboutOutput, err error)
	UpdateAbout(ctx context.Context, in model.AboutOutput) (err error)
}

var localAbout IAbout

func About() IAbout {
	if localAbout == nil {
		panic("implement not found for interface IAbout, forgot register?")
	}
	return localAbout
}

func RegisterAbout(i IAbout) {
	localAbout = i
}
