// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_blog/internal/model"
	"go_blog/internal/model/entity"
)

type ICategory interface {
	GetCategoryList(ctx context.Context) (out []*entity.Category, err error)
	ShowCategory(ctx context.Context, page, size int) (out *model.AllCategoryOutput, err error)
	AddCategory(ctx context.Context, name string) (err error)
	UpdateCategory(ctx context.Context, id int, name string) (err error)
	DeleteCategory(ctx context.Context, id int) (err error)
}

var localCategory ICategory

func Category() ICategory {
	if localCategory == nil {
		panic("implement not found for interface ICategory, forgot register?")
	}
	return localCategory
}

func RegisterCategory(i ICategory) {
	localCategory = i
}
