// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_blog/internal/model"
)

type IComment interface {
	Comment(ctx context.Context, in model.CommentInput) (err error)
	CommentList(ctx context.Context) (out *model.CommentListOutput, err error)
}

var localComment IComment

func Comment() IComment {
	if localComment == nil {
		panic("implement not found for interface IComment, forgot register?")
	}
	return localComment
}

func RegisterComment(i IComment) {
	localComment = i
}
