// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_blog/internal/model"
)

type IIndex interface {
	CategoryAndTag(ctx context.Context) (out *model.CategoryAndTagOutput, err error)
}

var localIndex IIndex

func Index() IIndex {
	if localIndex == nil {
		panic("implement not found for interface IIndex, forgot register?")
	}
	return localIndex
}

func RegisterIndex(i IIndex) {
	localIndex = i
}
