// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_blog/internal/model"
)

type ITags interface {
	Tags(ctx context.Context, page, size int) (out *model.AllTagsOutput, err error)
	AddTags(ctx context.Context, name, color string) (err error)
	UpdateTags(ctx context.Context, id int, name, color string) (err error)
	DeleteTags(ctx context.Context, id int) (err error)
}

var localTags ITags

func Tags() ITags {
	if localTags == nil {
		panic("implement not found for interface ITags, forgot register?")
	}
	return localTags
}

func RegisterTags(i ITags) {
	localTags = i
}
