// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Category is the golang structure for table category.
type Category struct {
	Id   int64  `json:"id"   description:""`
	Name string `json:"name" description:""`
}
