// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Tag is the golang structure for table tag.
type Tag struct {
	Id    int64  `json:"id"    description:""`
	Name  string `json:"name"  description:""`
	Color string `json:"color" description:"标签颜色(可选)"`
}
